"""
The text of a pull request: title, commit message and a description that carries the evidence, so a reviewer who has never opened Quanta can decide.

Nothing here is generated by a model. It is assembled from the finding, the scoring breakdown, the recorded exposure and the diff, and it says plainly
what Quanta did and did not check.
"""


def _pct(v):
    return f"{v * 100:.1f}%" if isinstance(v, (int, float)) else "n/a"


def _title_summary(kind, summary):
    if kind == "dependency-upgrade":
        return f"upgrade {summary['package']} to {summary['to']}"
    return summary.get("headline") or "fix a security finding"


def commit_title(pol, kind, summary):
    s = _title_summary(kind, summary)
    if pol["commit"]["style"] == "conventional":
        return ("fix(deps): " if kind == "dependency-upgrade" else "fix(security): ") + s
    return s[:1].upper() + s[1:]


def pr_title(pol, kind, summary, finding_ids):
    ids = ", ".join(finding_ids[:3]) + (f" +{len(finding_ids) - 3}" if len(finding_ids) > 3 else "")
    return f"{commit_title(pol, kind, summary)} [{ids}]"[:250]


def commit_message(pol, kind, summary, finding_ids, approver=None):
    msg = commit_title(pol, kind, summary) + "\n\n" + (summary.get("commit_body") or "Security fix proposed by Quanta.") + "\n\nQuanta findings: " + ", ".join(finding_ids)
    if pol["commit"].get("sign_off") and approver:
        msg += f"\n\nSigned-off-by: {approver}"
    return msg


def verify_steps(pol, summary):
    if summary.get("kind") == "dependency-upgrade" or summary.get("package"):
        cmd = (pol.get("verify_commands") or {}).get(summary.get("ecosystem") or "")
        out = []
        if cmd:
            out.append(f"`{cmd.format(package=summary['package'], version=summary['to'])}`")
        out.append("The test suite passes with the new version.")
        return out
    return summary.get("verify") or ["Run the tests that cover the changed code, including a case that reproduces the original problem."]


def body(pol, proposal, findings, reach, app):
    """proposal: the stored row (files, summary, kind, created_by, approved_by...). findings: compact scored findings for the proposal's finding ids."""
    s, kind = proposal["summary"], proposal["kind"]
    L = ["## Summary", ""]
    if kind == "dependency-upgrade":
        how = "a direct dependency" if s.get("direct") else ("a transitive dependency" + (f" pulled in by {', '.join(s['pulled_in_by'])}" if s.get("pulled_in_by") else ""))
        L.append(f"Upgrade `{s['package']}` from `{s.get('from') or 'unknown'}` to `{s['to']}` in **{proposal['application']}** ({s.get('ecosystem') or 'unknown ecosystem'}, {how}). "
                 f"This closes {len(findings)} finding(s)" + (f" covering {', '.join(s['cves'])}." if s.get("cves") else "."))
        if s.get("crosses_major"):
            L.append("\n> **Major version change.** Check the package's release notes for breaking changes before merging.")
    else:
        L.append(s.get("headline") or "Fix a security finding in first-party code.")
        if s.get("explanation"):
            L += ["", s["explanation"]]
    L += ["", "## Evidence", "", "| Finding | Issue | Severity | CVSS | EPSS | Known exploited | Fixed in |", "|---|---|---|---|---|---|---|"]
    for f in findings:
        L.append(f"| {f['id']} | {(f.get('cve') or f.get('title') or '')[:70]} | {f.get('severity')} | {f.get('cvss') if f.get('cvss') is not None else 'n/a'} | {_pct(f.get('epss'))} | "
                 f"{'yes' if f.get('kev') else 'no'} | {f.get('fixed_version') or '-'} |")
    top = max(findings, key=lambda x: x["score"]) if findings else None
    L += ["", "## Risk context", ""]
    if top:
        parts = ", ".join(f"{b['factor'].lower()} ({b['note']})" for b in top["breakdown"][:3])
        L.append(f"Priority **{top['tier']}**, score {top['score']} of 100. Largest contributors: {parts}.")
    ex = (reach or {}).get("exposure")
    if ex:
        stops = (reach or {}).get("stops") or []
        path = " -> ".join((st.get("label") or st["kind"].title()) + (f" ({st['name']})" if st.get("name") and st["kind"] != "internet" and st["kind"] != "application" else "") for st in stops)
        L.append(f"Exposure: **{ex}** ({reach.get('exposure_reason')}). Network path: {path if len(stops) > 2 else 'none recorded'}; verdict {reach.get('verdict')}.")
    if app.get("environment") or app.get("business_criticality"):
        L.append(f"Application: {app.get('environment') or 'environment not recorded'}, business criticality {app.get('business_criticality') or 'not recorded'}, owner {app.get('owner') or 'not recorded'}.")
    for a in (top or {}).get("assumptions", [])[:3]:
        L.append(f"- Assumption: {a}")
    L += ["", "## Changes", ""]
    for f in proposal["files"]:
        L.append(f"- `{f['path']}` (+{f['stats']['added']} / -{f['stats']['removed']})")
        for c in f.get("changes") or []:
            L.append(f"  - {c}")
    if s.get("lockfile_note"):
        L += ["", f"> {s['lockfile_note']}"]
    L += ["", "## How to verify", ""]
    L += [f"{i}. {v}" for i, v in enumerate(verify_steps(pol, {**s, "kind": kind}), 1)]
    L.append(f"{len(verify_steps(pol, {**s, 'kind': kind})) + 1}. After merge, rescan. Quanta marks the finding verified only when the next scan no longer reports it.")
    if s.get("validation"):
        v = s["validation"]
        L += ["", "## Notes from the author of the fix", "", "These are the fix author's statements, not test results."]
        for k, label in (("confirmed_vulnerable", "Confirmed the problem exists"), ("business_logic", "Behaviour that must not change"), ("risks", "Risks")):
            val = v.get(k)
            if val not in (None, "", []):
                L.append(f"- {label}: {val if not isinstance(val, list) else '; '.join(map(str, val))}")
    L += ["", "## Rollback", "", "Revert this pull request. It changes only the files listed above."]
    L += ["", "## Process", ""] + [f"{i}. {st['text']}" for i, st in enumerate(pol["process"]["steps"], 1)]
    approved = f" Approved in Quanta by {proposal['approved_by']}." if proposal.get("approved_by") else ""
    L += ["", "---", pol["pull_request"]["provenance"] + approved]
    return "\n".join(L) + "\n"
