{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "quanta.fullname" . }}-web
  labels:
    {{- include "quanta.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "quanta.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- if .Values.worker.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "quanta.fullname" . }}-worker
  labels:
    {{- include "quanta.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "quanta.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
{{- end }}
