{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "quanta.fullname" . }}
  labels:
    {{- include "quanta.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "quanta.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.serviceMonitor.tokenSecretName }}
      bearerTokenSecret:
        name: {{ .Values.serviceMonitor.tokenSecretName }}
        key: token
      {{- end }}
{{- end }}
