"""
An OpenAPI 3 document for a service, generated from what traffic showed.

It states only what was observed: paths and methods, path and query parameter NAMES, the response property names seen (their types are not known, so they are left
untyped), the status classes seen (2XX, 4XX, 5XX) and the authentication mechanisms seen. Required-ness, formats, enumerations and descriptions are unknown and are not
invented. Each operation also carries x-quanta-* extensions: whether a hand-written specification already documents it, the call count and dates, and the data classes
(under your framework) its responses carry. Review and complete it before publishing; it is a head start for the API office, not a contract.
"""
import re

from remediation.apisec import classify

_AUTH_SCHEMES = {"bearer": {"type": "http", "scheme": "bearer"}, "basic": {"type": "http", "scheme": "basic"}, "oauth2": {"type": "http", "scheme": "bearer", "description": "OAuth 2 access token (observed as a bearer credential)"},
                 "mtls": {"type": "mutualTLS"}, "api-key": {"type": "apiKey", "in": "header", "name": "X-API-Key", "description": "An API key was observed; the header name is not known - confirm it."},
                 "cookie": {"type": "apiKey", "in": "cookie", "name": "session", "description": "A session cookie was observed; the cookie name is not known - confirm it."}}


def build(service, endpoints, classes, specs=()):
    eps = [e for e in endpoints if e["service"] == service and e["observed"]]
    if not eps:
        return None
    servers, schemes = [], {}
    for s in specs:
        if s["service"] == service:
            servers = [{"url": u} for u in (s.get("meta") or {}).get("servers") or []][:3]
    if not servers and "." in service:
        servers = [{"url": f"https://{service}"}]
    paths_doc = {}
    for e in sorted(eps, key=lambda x: (x["template"], x["method"])):
        obs = e["obs"]
        op = {"summary": f"Observed {e['calls_total']:,} time(s) between {e['first_seen']} and {e['last_seen']}", "x-quanta-documented": e["in_spec"], "x-quanta-observed-calls": e["calls_total"],
              "x-quanta-first-seen": e["first_seen"], "x-quanta-last-seen": e["last_seen"]}
        params = [{"name": n, "in": "path", "required": True, "schema": {"type": "string"}} for n in re.findall(r"\{([^{}]+)\}", e["template"])]
        params += [{"name": q, "in": "query", "schema": {"type": "string"}} for q in obs["query_params"]]
        if params:
            op["parameters"] = params
        if obs["request_fields"] and e["method"] in ("POST", "PUT", "PATCH"):
            op["requestBody"] = {"content": {"application/json": {"schema": {"type": "object", "properties": {f: {} for f in obs["request_fields"]}}}}}
        resp = {}
        for cls, n in sorted(obs["status_counts"].items()):
            r = {"description": f"Seen {n:,} time(s)"}
            if cls == "2xx" and obs["response_fields"]:
                r["content"] = {"application/json": {"schema": {"type": "object", "properties": {f: {} for f in obs["response_fields"]}}}}
            resp[cls.upper()] = r
        op["responses"] = resp or {"default": {"description": "Status not recorded"}}
        mech = [m for m in obs["auth_counts"] if m != "none"]
        if mech:
            op["security"] = [{m: []} for m in mech]
            for m in mech:
                schemes[m] = _AUTH_SCHEMES.get(m, {"type": "http", "scheme": m, "description": "Observed; confirm the scheme."})
        elif obs["auth_counts"].get("none"):
            op["security"] = []
            op["x-quanta-note"] = "Requests with no credentials were observed on this operation."
        d = classify.assess_data(obs["detected"], obs["response_fields"], classes)
        if d["classes"]:
            op["x-quanta-data-classes"] = [c["name"] for c in d["classes"]]
        if d["unclassified"]:
            op["x-quanta-unclassified-data"] = d["unclassified"]
        paths_doc.setdefault(e["template"], {})[e["method"].lower()] = op
    doc = {"openapi": "3.0.3", "info": {"title": f"{service} (generated from observed traffic)", "version": "observed",
                                        "description": "Generated by Quanta from records it was given. Types, required properties and descriptions are unknown and were not invented. Review before publishing."},
           "paths": paths_doc}
    if servers:
        doc["servers"] = servers
    if schemes:
        doc["components"] = {"securitySchemes": schemes}
    return doc
