"""
A single, unified real activity log: who did what, to what, and when - across every
admin mutation in this app (asset ownership/facing/environment/remediation-schedule
edits, exception revocation, remediation approval/rejection, login attempts, bulk
asset-policy applies, remediation triggers).

Before this module, "who did what when" was scattered and incomplete: remediation_approvals
and exceptions each captured SOME of it in their own record shape, but
remediation/inventory/asset_inventory.py's set_owner/set_facing/set_environment recorded
only the new value - never who changed it or when - and there was no login-attempt log
anywhere at all. KNOWLEDGE_TRANSFER.md and cli/README.md both already named this as a
known, unbuilt gap before this module closed it.

This module doesn't replace any per-workflow record (approvals/exceptions keep their own
approved_by/rejected_by/requested_by fields, which stay authoritative for those
workflows) - it's an additive, append-only feed every mutation ALSO writes to, so there's
one real place to see everything that happened. remediation/enrichment/
activity_insights.py's real anomaly detection reads from this feed.

Persistence: a single local JSON file (remediation/audit/activity_log.json) - append-only,
never edited or deleted after the fact (an audit log you can rewrite isn't an audit log).
Gitignored (see .gitignore) the same way .vulnhunter/logs/ already is: this is real
runtime output generated by using the app, not seed/reference data that belongs in a
fresh checkout.
"""
import datetime
import json
from pathlib import Path

from remediation.utils.file_lock import FileLock

DEFAULT_LOG_PATH = Path(__file__).resolve().parent / "activity_log.json"


def _load(path=None):
    # Resolved inside the body (not as a bound default parameter) so that patching
    # DEFAULT_LOG_PATH in tests actually takes effect for every caller that omits
    # `path` - same gotcha as every other store module in this repo.
    path = Path(path) if path is not None else DEFAULT_LOG_PATH
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def _save(entries, path=None):
    path = Path(path) if path is not None else DEFAULT_LOG_PATH
    path.write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")


def record_activity(actor, action, target=None, details=None, path=None, as_of=None):
    """Appends one real activity record and returns it.

    `actor`: the real logged-in user's email, or a real identifier for an
    unauthenticated event (e.g. the attempted email on a failed login) - never
    fabricated, "unknown" if truly unavailable.
    `action`: a short, machine-readable, dotted verb (e.g. "asset.set_owner",
    "exception.revoke", "login.success", "login.failure", "remediation.trigger").
    `target`: whatever the action was performed on (an asset name, exception ID,
    finding ID) - None if the action has no single target (e.g. a login attempt).
    `details`: an optional, already-real dict describing what changed (e.g.
    {"owner": "New Name", "team": "New Team"}) - never a place to store a password or
    other secret."""
    # Locked for the full read-modify-write cycle, not just the final write: two
    # concurrent real actions (two admins editing different assets at nearly the same
    # moment, say) would otherwise both read the same `entries`, both compute the same
    # next `id`, and whichever saves last would silently overwrite the other's real
    # activity record - an audit log that can lose entries under real concurrent use
    # isn't one. See remediation/utils/file_lock.py's own docstring for why this is a
    # lock file, not a database transaction.
    lock_path = Path(path) if path is not None else DEFAULT_LOG_PATH
    with FileLock(lock_path):
        entries = _load(path)
        entry = {
            "id": len(entries) + 1,
            "actor": actor or "unknown",
            "action": action,
            "target": target,
            "details": details or {},
            "timestamp": (as_of or datetime.datetime.now(datetime.timezone.utc)).isoformat(),
        }
        entries.append(entry)
        _save(entries, path)
    return entry


def list_activity(path=None, actor=None, action=None, limit=None):
    """Returns entries newest-first, optionally filtered by an exact actor and/or
    action match. `limit` caps the result count after filtering."""
    entries = list(reversed(_load(path)))
    if actor:
        entries = [e for e in entries if e["actor"] == actor]
    if action:
        entries = [e for e in entries if e["action"] == action]
    if limit is not None:
        entries = entries[:limit]
    return entries
