"""
A single, unified real activity log: who did what, to what, and when - across every
admin mutation in this app (asset ownership/facing/environment/remediation-schedule
edits, exception revocation, remediation approval/rejection, login attempts, bulk
asset-policy applies, remediation triggers).

Before this module, "who did what when" was scattered and incomplete: remediation_approvals
and exceptions each captured SOME of it in their own record shape, but
remediation/inventory/asset_inventory.py's set_owner/set_facing/set_environment recorded
only the new value - never who changed it or when - and there was no login-attempt log
anywhere at all. KNOWLEDGE_TRANSFER.md and cli/README.md both already named this as a
known, unbuilt gap before this module closed it.

This module doesn't replace any per-workflow record (approvals/exceptions keep their own
approved_by/rejected_by/requested_by fields, which stay authoritative for those
workflows) - it's an additive, append-only feed every mutation ALSO writes to, so there's
one real place to see everything that happened. remediation/enrichment/
activity_insights.py's real anomaly detection reads from this feed.

Persistence is the shared local SQLite database (see remediation/utils/db.py),
append-only - never edited or deleted after the fact (an audit log you can rewrite
isn't an audit log). Previously a flat JSON file (gitignored, since this is real
runtime output generated by using the app, not seed/reference data that belongs in a
fresh checkout) - the shared DB file is gitignored the same way (see .gitignore).
"""
import datetime
import json

from sqlalchemy import insert, select

from remediation.utils import db as db_module


def _row_to_record(row):
    record = dict(row)
    record["details"] = json.loads(record["details"]) if record.get("details") else {}
    return record


def record_activity(actor, action, target=None, details=None, engine=None, as_of=None):
    """Appends one real activity record and returns it (with its real DB-assigned id).

    `actor`: the real logged-in user's email, or a real identifier for an
    unauthenticated event (e.g. the attempted email on a failed login) - never
    fabricated, "unknown" if truly unavailable.
    `action`: a short, machine-readable, dotted verb (e.g. "asset.set_owner",
    "exception.revoke", "login.success", "login.failure", "remediation.trigger").
    `target`: whatever the action was performed on (an asset name, exception ID,
    finding ID) - None if the action has no single target (e.g. a login attempt).
    `details`: an optional, already-real dict describing what changed (e.g.
    {"owner": "New Name", "team": "New Team"}) - never a place to store a password or
    other secret.

    Unlike every other store in this repo, this doesn't take a FileLock: the old JSON
    version needed one because computing the next id required reading every existing
    entry first (`len(entries) + 1`) - two concurrent calls could read the same stale
    count and silently overwrite each other's entry. A single INSERT relying on a real
    DB autoincrement id has no such read-modify-write gap; SQLite's own transaction
    locking already makes it atomic."""
    engine = engine or db_module.get_engine()
    db_module.ensure_schema(engine)
    row = {
        "actor": actor or "unknown",
        "action": action,
        "target": target,
        "details": json.dumps(details or {}),
        "timestamp": (as_of or datetime.datetime.now(datetime.timezone.utc)).isoformat(),
    }
    with engine.begin() as conn:
        result = conn.execute(insert(db_module.activity_log), row)
        new_id = result.inserted_primary_key[0]
    return {**row, "id": new_id, "details": details or {}}


def list_activity(engine=None, actor=None, action=None, limit=None):
    """Returns entries newest-first, optionally filtered by an exact actor and/or
    action match. `limit` caps the result count after filtering."""
    engine = engine or db_module.get_engine()
    db_module.ensure_schema(engine)
    with engine.connect() as conn:
        rows = conn.execute(
            select(db_module.activity_log).order_by(db_module.activity_log.c.id.desc())
        ).mappings().all()
    entries = [_row_to_record(r) for r in rows]
    if actor:
        entries = [e for e in entries if e["actor"] == actor]
    if action:
        entries = [e for e in entries if e["action"] == action]
    if limit is not None:
        entries = entries[:limit]
    return entries
